const information = [

	{
		"category":'TWO_WHEELERS',
		"subcategory":['Standard Bikes','UnderBone','Power Bikes','Delivery Bikes','Dual Sport','Scooter'],
		"Standard Bikes":[
			{
				"name":'HAOJUE ELEGANT 125CC',
				"overview":'A product with a difference, designed with the Nigeria market and environment in mind. It is strong and powerful for dual purposes whether commercial or private use. Sleek, slides easily between cars, fast enough on the open road an whether it is in urban areas or to use small paths where no car can travel, the Haojue Elegant is just what you are looking  for.',
				"LWH":'2060 X 776 X 1075 ',
				"Wheelbase":'1285mm',
				"Ground Clearance":'168mm',
				"Curb Mass":'132kg',
				"Engine type":'Four stroke, air-cooled, single cylinder',
				"Bore x Stroke (mm)":"56.5mm X 49.5mm",
				"Displacement":'124ml',
				"Compression ratio":'9.01',
				"Maximum Power":'7.2kW',
				"Economical fuel consumption":'1.7 L/100km',
				"Maximum speed":'90 km/h',
				"Ignition type":'DC-CDI',
				"Fuel Tank":'12.5L',
				"imageUrl":['/boulos_ng/img/bikes/HAJUE_DH125.jpg','img/bikes/HAJUE_DH125.jpg']
			},
			{
				"name":"HAOJUE GLORY 125CC",
				"overview":'A modern design which ensures you have an extraordinary ride. EG Glory meets all your expectations with unbeatable excellence..',
				"Gear":'5years',
				"Starting System":'Electric/ kick start',
				"Displacement":'125cc',
				"Battery":'12V, 7A',
				"Engine type":'Four stroke, air-cooled, single cylinder',
				"Bore x Stroke (mm)":'56.5mm X 49.5mm',
				"Displacement":'124ml',
				"Compression ratio":'9.01',
				"Maximum Power":'7.2kW',
				"Economical fuel consumption":'1.7L/100km',
				"Maximum speed":'90 km/h',
				"Ignition type":'DC-CDI',
				"Fuel Tank":'12.5L',
				"imageUrl":['/boulos_ng/img/bikes/HAOJUE_ELEGANT_125CC.jpg','/boulos_ng/img/bikes/HAOJUE_ELEGANT_125CC.jpg']

			},
			
			{
				"name":"HAOJUE DH125",
				"overview":"",
				"Type":"Air-Cooled, 4-Stroke, 1-Cylinder, SOHC",
				"Bore x Stroke (mm)":"56.5mm x 49.5mm",
				"Gear":'5years',
				"Max. Power":"6.2kW@7500rpm(8.3HP@7500rpm)",
				"Max. Torque":"8.8NM@5500rpm(0.9kg-m@5500rpm)",
				"Starting System":'Electric/ kick start',
				"Displacement":'124ml',
				"Compression Ratio":"9.6:1",
				"Carburetor":"VM17",
				"Starting":"Kick & Electric Start",
				"Battery":'12V, 7A',
				"Engine type":'	Single Cylinder, Air-cooled, 4-Stroke',
				"Air Cleaner":"Non-Woven Fabric Element",
				"Lubrication System":"Wet Sump",
				"Type of rear brake":"Drum",
				"Rear":	"Swing Arm, Coil Spring, Oil Damped",	 
 				"Front": "Disc/Drum",
 				"Rear":	"Drum",
 				"Front tire": "2.75-18",
 				"Rear tire":	"90-18 51P",
 				"Fuel System":"Carburetor",
 				"Dimensions":"",
 				"Fuel Tank Capacity":"12.5L",
 				"Ignition":"CDI",
 				"Overall Length (mm)":	"2,040",	 	 	 
				"Overall Width (mm)":	"740",	 	 	 
				"Overall Height (mm)":	"1,150", 	 	 
				"Wheelbase (mm)":"1,285",	 	 	 
				"Ground Clearance (mm)":"175",
				"Seat Height":"760mm",	
				"Curb Mass":"135kg",
				 "Maximum Power":"7.4 kW (8000r/min)",
				 "Maximum Torque":"9.6 Nm (6500r/min)",
				"Kerb Mass (kg)":"114",	 	 	  	 	 	 
				"Clutch":"Wet Multi-Plate Type",
				"Transmission"	: "5-Speed, Return Shift",
				"Electrical":"",	 	 	 
				"Ignition Type":"CDI",	 	 	 
				"Spark Plug":	"NGK",
				"Bore X Stroke (mm)":""	, 	 	 
				"Battery":	"12V, 5Ah Maintenance Free",
				"imageUrl":['/boulos_ng/img/bikes/HAJUE_DH125.jpg','/boulos_ng/img/bikes/HAJUE_DH125.jpg']

			},
			{
				"name":"HAOJUE DMS125",
				"overview":"",
				"Type":"Air-Cooled, 4-Stroke, 1-Cylinder, SOHC",
				"Bore x Stroke (mm)":"56.5mm x 49.5mm",
				"Gear":'5years',
				"Max. Power":"6.2kW@7500rpm(8.3HP@7500rpm)",
				"Max. Torque":"8.8NM@5500rpm(0.9kg-m@5500rpm)",
				"Starting System":'Electric/ kick start',
				"Displacement":'124ml',
				"Compression Ratio":"9.5:1",
				"Carburetor":"VM17",
				"Starting":"Kick & Electric Start",
				"Battery":'12V, 7A',
				"Engine type":'Single Cylinder, Air-cooled, 4-Stroke',
				"Air Cleaner":"Non-Woven Fabric Element",
				"Lubrication System":"Wet Sump",
				"Type of rear brake":"Drum",
				"Rear":	"Swing Arm, Coil Spring, Oil Damped",	 
 				"Front": "Drum",
 				"Rear":	"Drum",
 				"Front tire": "2.75-18",
 				"Rear tire":	"90 / 90-18",
 				"Fuel System":"Carburetor",
 				"Dimensions":"",
 				"Fuel Tank Capacity":"10L",
 				"Ignition":"CDI",
 				"Overall Length (mm)":	"2,030",	 	 	 
				"Overall Width (mm)":	"750",	 	 	 
				"Overall Height (mm)":	"1,095", 	 	 
				"Wheelbase (mm)":"1,285",	 	 	 
				"Ground Clearance (mm)":"175",
				"Seat Height":"750mm",	
				"Curb Mass":"127kg",
				 "Maximum Power":"7.4 kW (8000r/min)",
				 "Maximum Torque":"9.6 Nm (6500r/min)",
				"Kerb Mass (kg)":"114",	 	 	  	 	 	 
				"Clutch":"Wet Multi-Plate Type",
				"Transmission"	: "5-Speed, Rotary Shift",
				"Electrical":"",	 	 	 
				"Ignition Type":"CDI",	 	 	 
				"Spark Plug":	"NGK",
				"Wheelbase":"1280",	 	
				"Ground Clearance":"175mm", 	 
				"Battery":	"12V, 5Ah Maintenance Free",
				"imageUrl":['/boulos_ng/img/bikes/HAJUE_DH125.jpg','/boulos_ng/img/bikes/HAJUE_DH125.jpg']

			},
			{
				"name":"HAOJUE_EXPRESS",
				"overview":"Integrated with many advanced technologies, not only owns supreme power, but also economical and durable.",
				"Type":"Air-Cooled, 4-Stroke, 1-Cylinder, SOHC",
				"Bore x Stroke (mm)":"52.4mm x 57.9mm",
				"Gear":'5years',
				"Max. Power":"6.2kW@7500rpm(8.3HP@7500rpm)",
				"Max. Torque":"8.8NM@5500rpm(0.9kg-m@5500rpm)",
				"Starting System":'Electric/ kick start',
				"Displacement":'125ml',
				"Compression Ratio":"9.5:1",
				"Carburetor":"VM17",
				"Starting":"Kick & Electric Start",
				"Battery":'12V, 7A',
				"Engine type":'Single Cylinder, Air-cooled, 4-Stroke',
				"Air Cleaner":"Non-Woven Fabric Element",
				"Lubrication System":"Wet Sump",
				"Type of rear brake":"Drum",
				"Rear":	"Swing Arm, Coil Spring, Oil Damped",	 
 				"Front": "Drum",
 				"Rear":	"Drum",
 				"Front tire": "2.75-17",
 				"Rear tire":	"3.00-17",
 				"Fuel System":"Carburetor",
 				"Dimensions":"",
 				"Fuel Tank Capacity":"13L",
 				"Ignition":"CDI",
 				"Overall Length (mm)":	"1,980",	 	 	 
				"Overall Width (mm)":	"753",	 	 	 
				"Overall Height (mm)":	"1,078", 	 	 
				"Wheelbase (mm)":"1,285",	 	 	 
				"Ground Clearance (mm)":"175",
				"Seat Height":"794mm",	
				"Curb Mass":"117kg (Spoke Wheel), 120kg (Cast Wheel)",
				 "Maximum Power":"7.0kW (7500r/min)",
				 "Maximum Torque":"10N m (5500r/min)",
				"Kerb Mass (kg)":"114",	 	 	  	 	 	 
				"Clutch":"Wet Multi-Plate Type",
				"Transmission"	: "5-Speed, Return Shift",
				"Electrical":"",	 	 	 
				"Ignition Type":"CDI",	 	 	 
				"Spark Plug":	"NGK",
				"Wheelbase":"1243",	 	
				"Ground Clearance":"164mm", 	 
				"Battery":	"12V, 5Ah Maintenance Free",
				"imageUrl":['/boulos_ng/img/bikes/HAJUE_DH125.jpg','/boulos_ng/img/bikes/HAJUE_DH125.jpg']

			},


		],
		"UnderBone":[
			{
				"name":'HAOJUE UD 110',
				"overview":'A unique design with newly developed engine and powerful climbing performance. The patent frame guarantees stable center of gravity hence no matter driving at low or high speed, the driver can enjoy the steadiness and comfort.',
				"Type":"Air-Cooled, 4-Stroke, 1-Cylinder, SOHC",
				"Bore x Stroke (mm)":"52.4mm x 57.9mm",
				"Gear":'5years',
				"Maximum Power":"6.2kW@7500rpm(8.3HP@7500rpm)",
				"Maximum Torque":"8.8NM@5500rpm(0.9kg-m@5500rpm)",
				"Starting System":'Electric/ kick start',
				"Displacement":'107m',
				"Starting":"Kick & Electric Start",
				"Battery":'12volt, 5Amp',
				"Engine type":'4 stroke Single cylinder air cooled horizontal ',
 				"Fuel Tank Capacity":"1.28( economic speed/ 100km)",
				"Speed":"80km/h",
				"Maximum Power":"Alloy Wheels",
				"Maximum Torque":"10N m (5500r/min)",
				"Transmission"	: "5-Speed, Return Shift",
				"Wheelbase":"Alloy Wheels",	 		 
				"Battery":	"12V, 5Ah Maintenance Free",
				"imageUrl":['/boulos_ng/img/bikes/HAOJUE_UD_110.png','/boulos_ng/img/bikes/HAOJUE_UD_110.png']
			},
			{
				"name":'HAOJUE LUCKY 110CC',
				"overview":'In countries where the most reliable means of daily transportation are small bikes, the Haojue 110 is extremely popular. Who are we to argue with millions of satisfied consumers? Affordable, dependable, it is ideal to make way out of everyday jams and traffics with ease  and pleasure ride experience.',
				"Bore x Stroke (mm)":"1909 x 677 x 1088",	 	 
				"Curb weight (Kg)":	"104",	 	 	 
				"Mode of ignition":	"DC-CDI",	 	 	 
				"Wheelbase (mm)":	"1218",	 	 	 
				"Ground Clearance (mm)":"120",	 	 	 
				"Fuel Tank Capacity(L)":"4.7",	 	 	 
				"Type of front brake":"Drum",	 	 	 
				"Starter system":"Electric/kick start",	 	 
				"Engine Type":"Single cylinder, air cooling, four strokes",
				"Engine Displacement (ml)":	"107",	 	 	 
				"Maximum Power":	"5.2/8000",	 	 	 
				"Maximum Speed (Km/h)":">80",		 	 	 	
				"Compression ratio":"9.1:1",		 	 	 
				"Transmission":	"reciprocating four –gear type",
				"Type of clutch":	"wet auto centrifuge type",
				"Type of carburetor":"VM type",	 	 	 
				"Battery Specification":"12V, 5Ah",
				"imageUrl":['/boulos_ng/img/bikes/HAOJUE_LUCKY_110CC.png','/boulos_ng/img/bikes/HAOJUE_LUCKY_110CC.jpg']
			},
			{
				"name":'HAOJUE LUCKY PLUS',
				"overview":'The Haojue Lucky Plus has taken the Underbone Motorcycles to a whole new level, with more power and features. It still maintains the superior quality of the Haojue Lucky you love.',
				"Engine Type":"Single Cylinder, Air-cooled, 4-Stroke",
				"Engine Displacement":	"107 ml",
				"Bore x Stroke":"52.4mm x 49.5mm",
				"Compression Ratio":	"9.1:1",
				"Transmission":	"4-Speed, Return Shift (During Running)",
				"Fuel System":	"Carburetor",
				"Starter System":	"Electric/Kick",
				"Fuel Tank Capacity":	"4.2 L",
				"Ignition System":	"CDI",
				"Overall Length":	"1900 mm",
				"Overall Width":	"725 mm",
				"Overall Height":	"1090 mm",
				"Wheelbase":"1225 mm",
				"Ground Clearance":	"141 mm",
				"Seat Height":	"755mm",
				"Curb Mass":	"103.7kg",
				"Maximum Power":"5.0 kW (7500r/min)",
				"Maximum Torque":	"8.0 Nm (4500r/min)",
				"Front Brake":	"Drum",
				"Rear Brake":	"Drum",
				"Front Tire":	"2.50-17",
				"Rear Tire":"80 / 90-16",
				"imageUrl":['/boulos_ng/img/bikes/Haojue-lucky-plus.jpg','/boulos_ng/img/bikes/HAOJUE_LUCKY_PLUS.jpg']
			},

		],
		"Power Bikes":[
			{
				"name":'SUZUKI INTRUDER M1800R',
				"overview":`The Intruder represents a welcome addition for those hooked on the M1800R’s muscular power plant and awesome performance, but seeking something more distinctive in style and appearance. it’s the overall design, size and simplicity gives it that premium presence.

							The Intruder in its full array is an attention catcher with a broad pulled back and slug cruiser chrome handler gives it a more relax feel. The retro style tinted mirror brings onboard that cool, sassy and classic nature that is made for the elite.

							 Its unrivaled capabilities are born from Suzuki's championship-winning race heritage. Each bike's magnificent performance begins with a 1783cc, 8-valve DOHC, 54-degree, liquid-cooled, V-Twin engine. The M109R’s engine is tuned to produce massive torque all the way from idle to redline, which translates into acceleration that you have to feel to believe. The big V-twin also produces a throaty, aggressive exhaust that identifies the M109R as a power cruiser beyond compare. 

							It’s available in two colors;

							Pearl vigor blue (B.O.S.S)
							Glass sparkle black`,
				"Engine Type":"4-stroke, 4-cylinder, liquid-cooled, DOHC",
				"Engine Displacement": 	"1340 cm3 (81.8 cu. in)",	 	 
				"Bore x Stroke (mm)": 	"81.0mm x 65.0mm",	 	 	 
				"Compression Ratio": 	"12.5 : 1",	 	 	 	 
				"Transmission": 	"6-speed constant mesh",	 	 
				"Overall Length":	"2190 mm (86.2 in)",
				"Overall Width": 	"735 mm (28.9 in)",	 	 	 
				"Overall Height": 	"1165 mm (45.9 in)",
				"Wheelbase":	"1480 mm (58.3 in)",	 	 	 
				"Ground Clearance": 	"120 mm ( 4.7 in)",
				"Seat Height":	"805 mm (31.7 in)",	 	 	 
				"Curb Mass" :	"266 kg (586 lbs)",	 	 	 
				"Rear" :"190/50ZR17M/C (73W), tubeless"	,
				"Maximum Power":'',
				"Ignition Type": 	"Electronic ignition (Transistorized)",
				"Fuel Tank": 	"21.0 L (5.5 US gal)",
				"imageUrl":['/boulos_ng/img/bikes/SuzukiIntruder.png','/boulos_ng/img/bikes/SUZUKI_INTRUDER_M1800R.jpg',]
			},
			{
				"name":'MOTO GUZZI V7 II STONE',
				"overview":`Introducing the new generation, one of the best-selling and popular “Eagle brand” models in the world.  A new range that raises the bar on safety and equipment. The V7 is fitted with a dual channel ABS system and MGCT (Moto Guzzi Traction Control). The new 6 speed gearbox, improved ergonomics and numerous other changes fully meet expectations in terms of aesthetics and riding pleasure, making the new V7 even more attractive. `,
				"Front wheel":	 	"18, 100/90",	 	 	 	 	 
				"Rear wheel":	 	'17", 130/80',	 	 	 	 	 
				"Fuel tank capacity":"5.8 gallons",
				"Reserve":" 1 gallon",	 	 	 	 	 	 
				"Minimum ground clearance":	"7.16 inches",	 	 	 	 	 
				"Dry weight":	"394.6",	 	 	 	 	 	 
				"Curb weight":	"436 pounds (198 kg)",
				"Fuel tank capacity":	"5.8 gallons (22 liters)",
				"Reserve":	"0.66 gallons (2.5 liters)",
				"Rear brake":	" 260 mm stainless steel disc, floating 2 piston calliper",
				"Wheels	":"Cast aluminum alloy multi-spoke black anodized Rims",
				"Wheelbase":	"1.449 mm",	 	 	 	 	 	 
				"Front suspension":	 "Telescopic hydraulic fork with 40 mm stanchions",
				"Rear suspension":	"Die-cast light alloy swing arm with 2 fully adjustable Bitubo shock absorbers",
				"Rear wheel travel": "118 mm",	 	 	 	 	 	 
				"Brake system":	 "Brembo",	 	 	 	 	 	 
				"Front brake":	 "320 mm floating stainless steel disc, caliper with 4 differently sized opposed",
				"Type":	 "90° V-twin 4-stroke",	 	 	 	 	 
				"Capacity":	 "744 cc",	 	 	 	 	 	 
				"Maximum Power": "35 kW (48HP) at 6,200 rpm	",
				"Maximum torque":"60/Nm at 2,800",	 	 	 	 	 
				"Gearbox":	"6-speed",	 	 	 	 	 	 
				"Frame"	: "Double cradle tubular frame in ALS steel with detachable rear subframe",
				"imageUrl":['/boulos_ng/img/bikes/Motoguzzi-v7-II-Stone.png','/boulos_ng/img/bikes/MOTO_GUZZI_V7_II_STONE.jpg',]
			},

			{
				"name":'SUZUKI GSX-S1000A',
				"overview":'The GSX-S1000A is sketched from the attributes of the 2005-2008 generation GSX-R1000. This super bike has the power of the track infused with the spirit of the street with technological component that supports all day riding with comfort. Born of a linage that stands for performance, power and generational evolution powered by 999cc engine that gives unimaginable power, four-cylinder power plant that is based on the legendary long stroke GSX-R1000 engine which makes it fit for ideal street riding.The GSX-S1000, a motorcycle built for real-world excitement. Inheriting the genuine engine and main components of the world-beating GSX-R1000, this thrilling machine puts the feel of world-beating performance in your hands. Equipped with a more powerful engine, the Suzuki advanced traction control system, KYB suspensions for Balance and Nissin brakes for that perfect control. GSX- S1000A is here to change the world of street motorcycles again.Available colorsRedGreyBlue',
				"Engine":	"999cc, four-stroke, liquid-cooled, DOHC, inline-four",
				"Bore x Stroke (mm)":	"73.4 mm x 59.0mm (2.9 in x 2.3 in)",
				"Compression Ratio":	"12.2 : 1",
				"Fuel System":"Suzuki fuel injection",
				"Starter":	"Electric",
				"Lubrication":	"Wet sump",
				"Transmission"	:"6-speed constant mesh",
				"Final Drive":	"O-ring type, sealed drive chain",
				"Suspension Front":	"Inverted telescopic, coil spring, oil damped",
				"Suspension Rear":	"Link type, coil spring, oil damped",
				"Brakes Front":	"Brembo, disc brake, twin rotor",
				"Brakes Rear":	"Disc brake, single rotor",
				"Tires Front":	"120/70ZR17M/C (58W) tubeless",
				"Tires Rear":	"190/50ZR17M/C (73W) tubeless",
				"Fuel Tank Capacity":"17.0 L (4.5 US gallons)",
				"Color":	"Metallic Triton Blue, Glass Sparkle Black / Candy Daring Red",
				"Ignition":	"Electronic ignition (Transistorized)",
				"Headlight": "12 V 60/55 W (H4)",
				"Maximum Power":"",
				"Tail":"Light LED",
				"Overall Length":	"2115 mm (83.3 in)",
				"Overall Width":	"795 mm (31.3 in)",
				"Overall Height":	"1,080 mm (42.5 in)",
				"Wheelbase":	"1460 mm (57.5 in)",
				"Ground Clearance":	"140 mm (5.5 in)",
				"imageUrl":['/boulos_ng/img/bikes/SUZUKI_GSX_S1000A_small.png','/boulos_ng/img/bikes/SUZUKI_GSX_S1000A.jpg',]
			},
			
		],
		"Delivery Bikes":[
			{
				"name":'SUZUKI INAZUMA GW250Z',
				"overview":`Suzuki Inazuma 250 offers agility, power and comfort in a pretty compact package. This sporty naked features an aggressive design language that inspires agility and speed. We especially like the sharp-cut lines of the fairing, the sculpted fuel tank and the tasty headlight. Not to mention the comfortable handlebar, the perfectly placed foot pegs and the spacious seat which help you get a fairly relaxed riding experience.

							The Suzuki Inazuma 250’s centre piece is a 248cc, four stroke, liquid-cooled, SOHC, fuel injected engine especially tuned to offer a perfect balance between power and efficiency rewarding you with an average fuel consumption of over 85 mpg. The engine is fed by a large capacity fuel tank (13.3litres) that offers a decent riding range. Inazuma is available in red and black colour.
								`,
				"Engine":"248cc, 4-stroke, 2-cylinder, liquid-cooled, SOHC",
				"Fuel System":	"Electronic fuel injection",
				"Starter":	"Electric",
				"DRIVE":"TRAIN",	 
				"Transmission":	"6-speed constant mesh",
				"Final Drive":	"Chain",
				"Maximum Power":"",
				"Bore x Stroke (mm)":"",
				"CHASSIS":"",	 
				"Suspension Front":"Telescopic, coil spring, oil damped",
				"Suspension Rear":	"Swingarm, coil spring, oil damped",
				"Brakes Front":	"Disc",
				"Brakes Rear":	"Disc",
				"Tires Front":	"110/80Z-17 M/C 57H, tubeless",
				"Tires Rear":	"140/70Z-17 M/C 66H, tubeless",
				"Fuel Tank Capacity"	:"13.3 L (3.5 US gallons)",
				"Color":"Candy Cardinal Red / Pearl Nebular Black",
				"ELECTRICAL":"",	 
				"Ignition":	"Electronic ignition (transistorized)",
				"DIMENSIONS AND CURB WEIGHT":"",
				"Overall Length":	"2145 mm (84.4 in)",
				"Overall Width":	"760 mm (29.9 in)",
				"Wheelbase":	"1430 mm (56.3 in)",
				"Ground Clearance":	"165 mm (6.5 in)",
				"Seat Height":	"780 mm (30.7 in)",
				"Curb Weight":	"183 kg (403.4 lbs)",
				"imageUrl":['/boulos_ng/img/bikes/SUZUKI_INAZUMA_GW250Z_new.jpg','/boulos_ng/img/bikes/SUZUKI_INAZUMA_GW250Z.png',]
			},
			{
				"name":'SUZUKI DR200SE',
				"overview":`The DR200SE is a well-known versatile bike boasting a strong off road heritage. A multi-purpose utility motorcycle, the DR200SE is built without compromise and designed for the rigorous conditions.

							The DR200SE’s 199cm3 single-cylinder air-cooled four-stroke engine provides just the right amount of torque and horsepower to power your ride with ease on dirt trails, and top-end power that allows confident open-road riding.
								`,
				"Engine Type":	"4-stroke, SOHC, single-cylinder, Twin Dome Combustion Chamber",
				"Engine Displacement":	"199cc",
				"Maximum Power":"",
				"Bore x Stroke (mm)":	"2.6 in x 2.3 in (66.0 mm x 58.4 mm)",
				"Compression Ratio":"9.4 : 1",
				"Transmission":	"5-speed",
				"Fuel System":  "Mikuni BST31",
				"Starter System":	"Electric",
				"Fuel Tank Capacity":"3.4 gal. (13 l) CA model: 3.3 gal. (12.5 l)",
				"Ignition System":	"Digital / CDI",
				"Overall Length":	"84.6 in. (2,150 mm)",
				"Overall Width":	"31.7 in. (805 mm)",
				"Overall Height":	"46.7 in. (1,185 mm)",
				"Wheelbase"	:"55.3 in. (1,405 mm)",
				"Ground Clearance":	"10.2 in. (260 mm)",
				"Seat Height":	"31.9 in. (810 mm)",
				"Curb Mass"	:"126.0 kg (277.8 pounds)",
				"Front Suspension":	"Telescopic, oil damped",
				"Rear Suspension":	"Oil damped, adjustable preload",
				"Front Brake":	"Single hydraulic disc",
				"Rear Brake":	"Mechanical drum",
				"Front Tire":	"70/100-21 44P",
				"Rear Tire":	"100/90-18 56P",
				"imageUrl":['/boulos_ng/img/bikes/HAOJUE_ELEGANT_125CC.jpg','/boulos_ng/img/bikes/HAOJUE_ELEGANT_125CC.jpg',]
			}

		],
		"Dual Sport":[
			{
				"name":'SUZUKI DR650',
				"overview":`The Suzuki DR650S is the best all-around, dual-purpose motorcycle available today. It is one of the most versatile motorcycles ever made, from commuting, courier work, weekend toy to all out hardcore adventure touring, the DR650SE is built to be able to handle it all.  Every DR650S is quality built by Suzuki and features a reliable, 644cc, oil-cooled, four-stroke, single engine carried in a strong steel, semi-double cradle frame. The telescopic fork and link-style rear suspension can tackle tough trails or urban roads.`,
				"MODEL CODE":	"DR650SEL9 DUAL SPORT",
				"ENGINE": "SINGLE CYLINDER,4 STROKE, SOHC, AIR- COOLED WITH SACS",
				"STARTER": "ELECTRIC",
				"Maximum Power":"",
				"Bore x Stroke (mm)":"",
				"TRANSMISSION": "5-SPEED CONSTANT MESH",
				"FRONT SUSPENSION":"TELESCOPIC, COIL SPRING, OIL DAMPED",
				"REAR SUSPENSION": "LINK TYPE	COIL SPRING, OIL DAMPED SPRING PRELOAD/ COMPRESSION",
				"FRONT BRAKES":	"TWIN-PISTON CALIPER,290MM FLOATING DISC",
				"REAR BRAKES":	"TWIN-PISTON CALIPER, 240MM FLOATING DISC",
				"FUEL CAPACITY"	:"13 LITRES",
				"COLOUR":	"VARIANT",
				"SEAT HEIGHT":	"885 MM",
				"LENGHT":	"2255 MM",
				"WIDTH":	"865 MM",
				"HEIGHT":	"1195 MM",
				"WET WEIGHT":"166 KG",
				"WHEEL BASE":	"1490 MM",
				"imageUrl":['/boulos_ng/img/bikes/SUZUKI_DR650.jpg','/boulos_ng/img/bikes/SUZUKI_DR650.jpg']
			}

		],
		"Scooter":[
			{
				"name":'ACCESS 125',
				"overview":`The Suzuki Access 125 is the best 125cc scooter available in the Nigerian market. The scooter is a perfect blend of style, performance, practicality and fuel efficiency. The overall design of the scooter is stylish and offers an impressive performance and mileage. If you are looking for a stylish and powerful scooter for daily commuting, then the Suzuki Access 125 should be your choice.`,
				"ENGINE Engine": "124cc",
				 "No of cylinder": "1 Max power, 8.85bhp @7000rpm",
				 "Max torque": "10.1nm @5000rpm",
				 "Valves per cylinder":  "2",
				 "Fuel delivery": "Carburetor",
				 "Cooling system": "Air cooled",
				 "Starting mechanism": "Electric/kick start",
				 "DIMENSION AND WEIGHT" :"",
				 "Kerb weight" :"101kg",
				 "Length": "1870mm",
				 "Width":"655mm",
				 "Height": "1160mm",
				 "Wheelbase": "1265mm",
				 "Ground clearance" :"160mm",
				 "Seat height": "773mm",
				 "FUEL CONSUMPTION":"",
				 "Fuel tank capacity": "5.6L Reserve",
				 "fuel capacity": "1L",
				 "Mileage": "64 kmpl Overall riding",
				 "range": "358.4km",
				 "BRAKING Front brake type": "Disc",
				 "Rear brake type":"Drum" ,
				 "Front disc/drum size": "240mm",
				 "Rear disc/drum size": "120mm",
				 "Maximum Power":"",
				"Bore x Stroke (mm)":"",
				 "ELECTRICAL/ WHEEL AND TYRE Battery": "12v, 3AH Maintenance free Headlight 12v 35/35w",
				  "Tail light": "",
				  "Bulb Wheel size":" 12inc",
				  "Wheel type": "Alloy",
				  "Front tyre":"90/90 -12-Tubeless",
				  "Front tyre": "90/100 -10-Tubeless", 
					"imageUrl":['/boulos_ng/img/bikes/Access125_new.jpg','/boulos_ng/img/bikes/Access125.png']
			}

		],

	},
	{
		"category":'THREE_WHEELERS',
		"subcategory":['Galaxy Cargo Tricycle'],
		"Galaxy Cargo Tricycle":[
			{
				"name":'Galaxy Cargo Tricycle',
				"overview":`Boulos enterprises limited is known for the assembling and distribution of quality automobile products for over 60 years in Nigeria. Recent addition to its range of products is the new Galaxy Cargo Tricycle.  The new Galaxy Cargo tricycle is constructed with well selected material for maximum strength and performance.

				The Cargo Tricycle is packed with unbeatable features to help your business move. It can Carry anything from:  lightweight Goods, Farm produce, Drinks, Water, Food etc. anywhere in Nigeria. The major unique feature of the Galaxy Tricycle is the single cylinder and air-cooling engine quality.

				The Galaxy is Rugged with strong body to withstand high loading capacity, durable (Strong suspension and strong chassis to support the load carrying capacity), efficient and affordable. It is available in 2 variants of 150ccc and 200cc for lightweight goods and heavy-duty goods.`,
				"Engine Type":	"200CC AIR-COOLING KING",
				"Bore x Stroke (mm)":	"63 x 64.5",
				"Compression Ratio	":"9:0:1"	,
				"Maximum Power":	"10.5KW/7500RPM",
				"Max Torque"	:"15.5N.M/5500RPM",
				"Idle Speed":	"1500± 150R/MIN",
				"Leaf Spring":	"16KG ONE PCS (HEAVY DUTY)",
				"Rear Carrier Size":	"1.25M x 1.7M",
				"Brake Way": 	"DRUM BRAKE",
				"Tire Size":	"5.0-12 (TNT SUPPLIER)",
				"Front Shock Absorber":	"50MM DIAMETER STYLE WITH REINFORCEMENT PLATE",
				"Rear Bridge":	"5 BOLT TS SEMI-SUSPENSION STYLE",
				"Foldable Long Seat	WITHOUT":"",
				"Maximum Loading Weight Capacity":	"600KG",
				"Fuel Tank Capacity"	:"17 LITERS",
				"Colour Available":"RED, BLUE, ARMY GREEN, ORANGE",
				"imageUrl":['/boulos_ng/img/bikes/galaxy_new.jpg','/boulos_ng/img/bikes/galaxy.png']
			}

		]
	},
	{
		"category":'FOUR_WHEELERS',
		"subcategory":['Suzuki Super Carry'],
		"Suzuki Super Carry":[
			{
				"name":'SUZUKI SUPER CARRY',
				"overview":'A product with a difference, designed with the Nigeria market and environment in mind. It is strong and powerful for dual purposes whether commercial or private use. Sleek, slides easily between cars, fast enough on the open road an whether it is in urban areas or to use small paths where no car can travel, the Haojue Elegant is just what you are looking  for.',
				"LWH":'2060 X 776 X 1075 ',
				"Wheelbase":'1285mm',
				"Ground Clearance":'168mm',
				"Curb Mass":'132kg',
				"Engine type":'Four stroke, air-cooled, single cylinder',
				"Bore x Stroke (mm)":'',
				"Maximum Power":"",
				"imageUrl":['/boulos_ng/img/bikes/SUZUKI_SUPER_CARRY.jpg','/boulos_ng/img/bikes/SUZUKI_SUPER_CARRY.jpg']
			}
		]
	}



]

		

	
