// "name":'HAOJUE ELEGANT 125CC',
// 				"overview":'A product with a difference, designed with the Nigeria market and environment in mind. It is strong and powerful for dual purposes whether commercial or private use. Sleek, slides easily between cars, fast enough on the open road an whether it is in urban areas or to use small paths where no car can travel, the Haojue Elegant is just what you are looking  for.',
// 				"LWH":'2060 X 776 X 1075 ',
// 				"Wheelbase":'1285mm',
// 				"Ground Clearance":'168mm',
// 				"Curb Mass":'132kg',
// 				"Engine type":'Four stroke, air-cooled, single cylinder',
// 				"Bore x Stroke (mm)":"56.5mm X 49.5mm",
// 				"Displacement":'124ml',
// 				"Compression ratio":'9.01',
// 				"Maximum Power":'7.2kW',
// 				"Economical fuel consumption":'1.7 L/100km',
// 				"Maximum speed":'90 km/h',
// 				"Ignition type":'DC-CDI',
// 				"Fuel Tank":'12.5L',